### ISSUE TITLE
Incompatible architecture (have 'arm64', need 'x86_64') in M1 mac

### ISSUE THREAD

**Issue by bibash28** [spruceid/didkit#297]
[mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64') in Flutter] 
<img width="999" alt="image" src="https://user-images.githubusercontent.com/18188709/168225758-1432cbf8-daab-46b2-b6ee-0e890b95912c.png">

**Comment by Sean-Snow** [comment]
change arch
env /usr/bin/arch -arm64 /bin/zsh
env /usr/bin/arch -x86_64 /bin/zsh
clean and build

**Comment by bibash28** [comment]
@Sean-Snow.. changing the arch didn't solve the issue...

**Comment by TalebRafiepour** [comment]
Same Issue on Macbook M1 pro:
```
error: Invalid argument(s): Failed to load dynamic library 'libdidkit.so': dlopen failed: library "libdidkit.so" not found, stack: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
I/flutter ( 5031): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
I/flutter ( 5031): #2      lib (package:didkit/didkit.dart:9:22)
I/flutter ( 5031): #3      lib (package:didkit/didkit.dart)
I/flutter ( 5031): #4      key_to_did (package:didkit/didkit.dart:29:20)
I/flutter ( 5031): #5      key_to_did (package:didkit/didkit.dart)
I/flutter ( 5031): #6      DIDKit.keyToDID (package:didkit/didkit.dart:119:17)
```

**Comment by bibash28** [comment]
@sbihel I am trying to build for android in M1 mac...  Let me share the commands

```
echo "Checking for rustup installation and setting rust to nightly."
if ! command -v rustup &>/dev/null; then
  echo "rustup"
  if ! command -v curl &>/dev/null; then
    echo "curl"
    if [[ "$OSTYPE" == "darwin"* ]]; then
      echo "rust darwin"
      brew install curl
    else
      echo "rust linux"
      sudo apt install curl -yet
    fi
  fi

  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

fi
rustup default nightly

if [[ "$*" == *-android* ]]; then
  echo "Build didkit for Android"
  cd lib/flutter
  fvm use 2.10.1
  fvm flutter pub get
  cd -
  make -C lib install-rustup-android
  make -C lib ../target/test/java.stamp
  make -C lib ../target/test/android.stamp
  make -C lib ../target/test/flutter.stamp
fi

cargo build

```

**Comment by sbihel** [comment]
You can drop `make -C lib ../target/test/flutter.stamp` in that script

**Comment by bibash28** [comment]
ok..

`make -C lib ../target/test/android.stamp`

is failing...


```
error: Invalid argument(s): Failed to load dynamic library 'libdidkit.so': dlopen failed: library "libdidkit.so" not found, stack: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
I/flutter ( 5031): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
I/flutter ( 5031): #2      lib (package:didkit/didkit.dart:9:22)
I/flutter ( 5031): #3      lib (package:didkit/didkit.dart)
I/flutter ( 5031): #4      key_to_did (package:didkit/didkit.dart:29:20)
I/flutter ( 5031): #5      key_to_did (package:didkit/didkit.dart)
I/flutter ( 5031): #6      DIDKit.keyToDID (package:didkit/didkit.dart:119:17)
```

**Comment by sbihel** [comment]
I meant, you can remove it.

**Comment by bibash28** [comment]
removing doesn't solve issue @sbihel

**Comment by sbihel** [comment]
Is it the same error? For which command?

**Comment by bibash28** [comment]
I still have this issue @sbihel @itsbalamurali 

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/18188709/197906109-e1723ca8-08ec-403d-a4de-5ed25853c967.png">

What I did?
I followed
https://github.com/spruceid/didkit/pull/315/commits/8cb30fd28069a97e9f5679c77a2f3c6d567e3e06
https://github.com/spruceid/didkit/pull/315/commits/c381070a97f8bd98c853bfed4e3220e08a5e78bc

**Comment by kangminhao** [comment]
I'm encountering the same issue when building an iOS framework.
Do someone fix this problem or find the solution?
